config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: "lists#index", as: :home
  resources :lists, only: [:index, :show, :new, :create] do
    resources :bookmarks, only: [:new, :create]
  end
  resources :bookmarks, only: [:destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :movie
  belongs_to :list
  validates :comment, length: { minimum: 6 }
  validates_uniqueness_of :list_id, scope: :movie_id
end

app/models/list.rb
class List < ApplicationRecord
  has_many :bookmarks
  has_many :movies, through: :bookmarks, dependent: :destroy
  has_one_attached :photo
  validates :name, uniqueness: true, presence: true
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :bookmarks
  validates :title, uniqueness: true, presence: true
  validates :overview, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  def new
    @list = List.find(params[:list_id])
    @bookmark = Bookmark.new
  end

  def create
    @bookmark = Bookmark.new(bookmark_params)
    @list = List.find(params[:list_id])
    @bookmark.list = @list
    if @bookmark.save
      redirect_to list_path(@list)
    else
      render :new
    end
  end

  def destroy
    @bookmark = Bookmark.find(params[:id])
    @bookmark.destroy
    redirect_to list_path(@bookmark.list)
  end

  private

  def bookmark_params
    params.require(:bookmark).permit(:comment, :list_id, :movie_id)
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  def index
    @lists = List.all
  end

  def show
    @list = List.find(params[:id])
  end

  def new
    @list = List.new
  end

  def create
    @list = List.new(list_params)
    if @list.save
      redirect_to list_path(@list)
    else
      render :new
    end
  end

  private

  def list_params
    params.require(:list).permit(:name, :bookmarks, :photo)
  end
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  def index
    @movies = Movie.all
  end

  def show
  end

  def new
  end

  def create
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/views/bookmarks/new.html.erb
<%= simple_form_for [@list, @bookmark] do |f| %>
  <%= f.association :movie %>
  <%= f.input :comment %>
  <%= f.submit "Submit bookmark", class: "btn btn-primary" %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/lists/index.html.erb
<% @lists.each do |list| %>
<% if list.photo.attached? %>
<%= cl_image_tag list.photo&.key, height: 300, width: 400, crop: :fill %>
<% else %>
<%= image_tag "https://source.unsplash.com/random", height: 300, width: 400, crop: :fill %>
<% end %>
<h2><%= link_to list.name, list_path(list) %></h2>
<% end %>

<%= link_to "Add a list", new_list_path %>

app/views/lists/new.html.erb
<%= simple_form_for @list do |f| %>
<%= f.input :name %>
<%= f.input :photo, as: :file %>
<%= f.submit :submit %>
<% end %>

<%= link_to "Back to the lists", home_path %>

app/views/lists/show.html.erb
<h2><%= @list.name %></h2>
<% if @list.photo.attached? %>
  <%= cl_image_tag @list.photo&.key, height: 300, width: 400, crop: :fill %>
  <% else %>
  <%= image_tag "https://source.unsplash.com/random", height: 300, width: 400, crop: :fill %>
<% end %>
<p><%@list.bookmarks.each do |bookmark|%></p>
<h3><%= bookmark.movie.title %></h3>
<img src="<%= bookmark.movie.poster_url %>" alt="">
<p><%= bookmark.movie.overview %></p>
<%= bookmark.comment %>
<%= link_to "Delete",
                  bookmark_path(bookmark),
                  method: :delete,
                  data: { confirm: "Are you sure?" } %>
<% end %>


<%= link_to "Add a movie", new_list_bookmark_path(@list) %>
<%= link_to "Back to the lists", home_path %>

app/views/movies/index.html.erb
<% @movies.each do |movie| %>
<h2><%= movie.title  %></h2>
<img src="#{movie.poster_url}" alt="">
<% end %>